# -*- coding: utf-8 -*-
"""Python Assignment 01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1220dHqiiWYGHZ6Y7WSHcQCDMHAyXEd_C

# PYTHON ASSIGNMENT 01

Implement at least 5-10 methods of all four containers (List, Dictionary, Tuple and Set).
The methods must be different from the methods discussed in class.

**L I S T S**
"""

mylist = ["apple", "banana", "cherry"]
print(type(mylist))

mylist = list(("apple", "banana", "cherry", "orange"))
print(mylist)

"""Acessing Lists"""

mylist = list(("apple", "banana", "cherry", "orange"))
print(mylist[0])
print(mylist[1])
print(mylist[2])
print(mylist[3])
mylist = ["apple", "banana", "cherry", "orange"]
print(mylist[-1])
print(mylist[-2])
print(mylist[-3])
print(mylist[-4])

mylist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(mylist[2:5])
print(mylist[:4])
print(mylist[2:])
print(mylist[-4:-1])

mylist = ["apple", "banana", "cherry"]
if "apple" in mylist:
  print("Yes, 'apple' is in list")
if "orange" in mylist:
  print("Yes, 'orange' is in list")
else:
  print("No, 'orange is not in list")

"""Change List Items"""

mylist = ["apple", "banana", "cherry"]
mylist[1] = "pomegranate"
print(mylist)

mylist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
mylist[1:4] = ["pomegranate", "watermelon"]
print(mylist)

mylist = ["apple", "banana", "cherry"]
mylist[1:3] = ["watermelon"]
print(mylist)

mylist = ["apple", "banana", "cherry"]
mylist.insert(2, "watermelon")
print(mylist)

"""Adding list items"""

mylist = ["apple", "banana", "cherry"]
mylist.append("orange")
print(mylist)

mylist = ["apple", "banana", "cherry"]
mylist.insert(1, "orange")
print(mylist)

mylist = ["apple", "banana", "cherry"]
tropical = ["mango", "pineapple", "papaya"]
mylist.extend(tropical)
print(mylist)

mylist = ["apple", "banana", "cherry"]
mytuple = ("kiwi", "orange")
mylist.extend(mylist)
print(mylist)

"""Remove List Items"""

mylist = ["apple", "banana", "cherry"]
mylist.remove("banana")
print(mylist)

mylist = ["apple", "banana", "cherry"]
mylist.pop(1)
print(mylist)

mylist = ["apple", "banana", "cherry"]
mylist.pop()
print(mylist)

mylist = ["apple", "banana", "cherry"]
del mylist[0]
print(mylist)

mylist = ["apple", "banana", "cherry"]
del mylist

mylist = ["apple", "banana", "cherry"]
mylist.clear()
print(mylist)

"""Loop Lists"""

mylist = ["apple", "banana", "cherry"]
for a in mylist:
  print(a)

mylist = ["apple", "banana", "cherry"]
for i in range(len(mylist)):
  print(mylist[i])

mylist = ["apple", "banana", "cherry"]
i = 0
while i < len(mylist):
  print(mylist[i])
  i = i + 1

mylist = ["apple", "banana", "cherry"]
[print(a) for a in mylist]

"""List Comprehension"""

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
listnew = []

for x in fruits:
  if "a" in x:
    listnew.append(x)

print(listnew)

fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
listnew = [x for x in fruits if "a" in x]
print(listnew)

listnew = [x for x in fruits if x != "apple"]
print(listnew)
listnew = [x for x in fruits]
print(listnew)
listnew = [x for x in range(10)]
print(listnew)
listnew = [x for x in range(10) if x < 5]
print(listnew)
listnew = [x.upper() for x in fruits]
print(listnew)
listnew = ['hello' for x in fruits]
print(listnew)
listnew = [x if x != "banana" else "orange" for x in fruits]
print(listnew)

"""List Sorting"""

mylist = ["orange", "mango", "kiwi", "pineapple", "banana"]
mylist.sort()
print(mylist)

mylist = [100, 50, 65, 82, 23]
mylist.sort()
print(mylist)

mylist = ["orange", "mango", "kiwi", "pineapple", "banana"]
mylist.sort(reverse = True)
print(mylist)

mylist = [100, 50, 65, 82, 23]
mylist.sort(reverse = True)
print(mylist)

def fruitsfunc(n):
  return abs(n - 50)

mylist = [100, 50, 65, 82, 23]
mylist.sort(key = fruitsfunc)
print(mylist)

mylist = ["banana", "Orange", "Kiwi", "cherry"]
mylist.sort()
print(mylist)

mylist = ["banana", "Orange", "Kiwi", "cherry"]
mylist.sort(key = str.lower)
print(mylist)

mylist = ["banana", "Orange", "Kiwi", "cherry"]
mylist.reverse()
print(mylist)

"""List Copying"""

mylist = ["apple", "banana", "cherry"]
newlist = mylist.copy()
print(newlist)

mylist = ["apple", "banana", "cherry"]
newlist = list(mylist)
print(newlist)

"""Joining Lists"""

lista = ["x", "y", "z"]
listb = [1, 2, 3, 4]

listc = lista + listb
print(listc)

lista = ["x", "y" , "z"]
listb = [1, 2, 3, 4]

for x in listb:
  lista.append(x)

print(lista)

lista = ["x", "y" , "z"]
listb = [1, 2, 3, r]

lista.extend(listb)
print(lista)

"""**D I C T I O N A R I E S**"""

mydict = {
  "brand": "Mercedes Benz",
  "model": "AMG GT 4-Door Coupe",
  "year": 2020,
  "colors": ["magnetic black", "solar beaam", "Hyacinth Red"]

}
print(mydict)
print(mydict["brand"])
print(len(mydict))
print(type(mydict))

mydict = {
  "brand": "Mercedes Benz",
  "model": "AMG GT 4-Door Coupe",
  "year": 2020,
  "year": 2021

}
print(mydict)

"""Access Items"""

mydict = {
  "brand": "Mercedes Benz",
  "model": "AMG GT 4-Door Coupe",
  "year": 2020,
  "colors": ["magnetic black", "solar beaam", "Hyacinth Red"]
}
x = mydict["model"]
x = mydict.get("model")
x = mydict.keys()
mydict["cost"] = "2.63Cr"
print(x) 
print(mydict)
mydict["year"] = 2021
print(x)
if "model" in mydict:
  print("Yes, 'model' is one of the keys in the 'mydict' dictionary")

"""Change Items"""

mydict = {
  "brand": "Mercedes Benz",
  "model": "AMG GT 4-Door Coupe",
  "year": 2020
}
mydict["year"] = 2018
mydict.update({"year": 2021})
print(mydict)

"""Add Items"""

mydict = {
  "brand": "Mercedes Benz",
  "model": "AMG GT 4-Door Coupe",
  "year": 2020
}
mydict["color"] = "red"
print(mydict)
mydict.update({"color": "vintage blue"})
print(mydict)
mydict.pop("model")
print(mydict)
mydict.popitem()
print(mydict)
del mydict["year"]
print(mydict)
#del mydict
#print(mydict) #error
mydict.clear()
print(mydict)

"""Loop Dictionaries"""

mydict = {
  "brand": "Mercedes Benz",
  "model": "AMG GT 4-Door Coupe",
  "year": 2020
}
for x in mydict:
  print(mydict[x])
for x in mydict.values():
  print(x)
for x in mydict.keys():
  print(x)
for x, y in mydict.items():
  print(x, y)

"""Copy Dictionaries"""

mydict = {
  "brand": "Mercedes Benz",
  "model": "AMG GT 4-Door Coupe",
  "year": 2020
}
newdict = mydict.copy()
print(newdict)
newdict = dict(mydict)
print(newdict)

"""Nested Dictionaries"""

family = {
  "father" : {
    "name" : "father",
    "year" : 1980
  },
  "mother" : {
    "name" : "mother",
    "year" : 1982
  },
  "brother" : {
    "name" : "brother",
    "year" : 2004
  }
}
print(family)

father = {
  "name" : "father",
  "year" : 1980
}
mother = {
  "name" : "mother",
  "year" : 1982
}
brother = {
  "name" : "brother",
  "year" : 2004
}

myfamily = {
  "father" : father,
  "mother" : mother,
  "brother" : brother
}

print(myfamily)

"""**T U P L E**"""

mytuple = ("apple", "banana", "cherry", "apple", "cherry")
print(mytuple)
print(len(mytuple))
print(type(mytuple))
mytuple = (("apple", "banana", "cherry", "apple", "cherry"))
print(mytuple)

"""Acess Tuples"""

mytuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(mytuple[1])
print(mytuple[-1])
print(mytuple[2:5])
print(mytuple[:4])
print(mytuple[2:])
print(mytuple[-4:-1])
if "apple" in mytuple:
  print("Yes, 'apple' is in the fruits 'mytuple' ")

"""Updating Tuples"""

a = ("apple", "banana", "cherry")
b = list(a)
b[1] = "kiwi"
a = tuple(a)
print(a)

mytuple = ("apple", "banana", "cherry")
b = list(mytuple)
b.append("orange")
mytuple = tuple(b)
print(mytuple)

"""Unpack Tuples"""

fruits = ("apple", "banana", "cherry")
(green, yellow, red) = fruits
print(green)
print(yellow)
print(red)

fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")
(green, yellow, *red) = fruits
print(green)
print(yellow)
print(red)

fruits = ("apple", "mango", "papaya", "pineapple", "cherry")
(green, *tropic, red) = fruits
print(green)
print(tropic)
print(red)

"""Loop Tuples"""

mytuple = ("apple", "banana", "cherry")
for i in range(len(mytuple)):
  print(thistuple[i])

i = 0
while i < len(mytuple):
  print(mytuple[i])
  i = i + 1

"""Join Tuples"""

tuple1 = ("a", "b" , "c", "d", "e")
tuple2 = (1, 2, 3, 4, 5)

tuple3 = tuple1 + tuple2
print(tuple3)

fruits = ("apple", "banana", "cherry")
newtuple = fruits * 2

print(newtuple)

"""**S E T S**"""

myset = {"apple", "banana", "cherry"}
mynewset={1,2,3,4,5}
mynewset1={True,False,None}
print(myset)
print(len(myset))
print(type(myset))
print(mynewset)
print(mynewset1)

myset = {"apple", "banana", "cherry", "apple"}
print(myset)

newone = {"abc", 34, True, 40, "male"}
print(newone)

myset = set(("apple", "banana", "cherry"))
print(myset)

"""Access Set Items"""

myset = {"apple", "banana", "cherry"}
for x in myset:
  print(x)
print("banana" in myset)

"""Adding & Removing Items to set"""

myset = {"apple", "banana", "cherry"}
myset.add("orange")
print(myset)

tropical = {"pineapple", "mango", "papaya"}
myset.update(tropical)
print(myset)

mylist = ["kiwi", "orange"]
myset.update(mylist)
print(myset)

myset = {"apple", "banana", "cherry", "orange"}
myset.remove("banana")
print(myset)
myset.discard("orange")
print(myset)
x = myset.pop()
print(x)
print(myset)
myset.clear()
print(myset)

setnew = {"apple", "banana", "cherry"}
del setnew
#print(setnew)  it will get error as the set is deleted

"""Loop & Joining Sets"""

myset = {"apple", "banana", "cherry"}

for x in myset:
  print(x)

set1 = {"a", "b" , "c"}
set2 = {1, 2, 3}

set3 = set1.union(set2)
print(set3)
set1.update(set2)
print(set1)
set1.intersection_update(set2)
print(set1)
finalset = set1.intersection(set2)
print(finalset)

x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
x.symmetric_difference_update(y)
print(x)
z = x.symmetric_difference(y)
print(z)

###   mani Deepak P
###   190137 / 190C2030045
###   CSE 1

"""                                      --The End--"""